services:
  s2:
    build:
      context: .
      dockerfile: Dockerfile.sen2cor
    image: s2-process-l2a
    container_name: s2_process_l2a
    env_file:
      - .env
    volumes:
      - ./configs:/workspace/configs
      - ./input:/workspace/input
      - ./output:/workspace/output
      - ./src:/workspace/src
    working_dir: /workspace
    command: ["/workspace/configs/pipeline.json"]

  s2-wine:
    build:
      context: ..
      dockerfile: SOFT_new/Dockerfile.sen2cor.wine
    image: s2-process-l2a-wine
    container_name: s2_process_l2a_wine
    env_file:
      - .env
    volumes:
      - ./configs:/workspace/configs
      - ./input:/workspace/input
      - ./output:/workspace/output
      - ./src:/workspace/src
    working_dir: /workspace
    command: ["/workspace/configs/pipeline.json"]
